default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "root" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  timeout: 5000

development:
  <<: *default
  database: good_night_development

test:
  <<: *default
  database: good_night_test

production:
  <<: *default
  database: good_night_production
  username: <%= ENV.fetch("DB_USERNAME") { "production_user" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "production_password" } %>
